/**
 * Code snippets generator for module polyfills
 */

import { getMainOnlyApis } from "./constants.js";

/**
 * Generate the electron polyfill code for the renderer process
 * This creates a module that properly exports electron APIs with ipcRenderer Worker support
 */
export function generateElectronSnippet(): string {
  const mainOnlyApis = getMainOnlyApis();

  return `
/**
 * Electron polyfill for Vite bundling
 * Auto-generated by plugin-vite-electron-renderer
 */

const electron = typeof require !== 'undefined'
  ? (() => {
    // Avoid bundler parsing the require call
    const _require = require;
    return _require("electron");
  })()
  : (() => {
    console.error(
      '[electron-renderer] Cannot load electron module. ' +
      'Make sure "nodeIntegration" is enabled in BrowserWindow webPreferences.'
    );
    return {};
  })();

// Proxy ipcRenderer for Web Worker environments
let _ipcRenderer;

if (typeof document === 'undefined') {
  // We're in a Worker - ipcRenderer doesn't work there
  _ipcRenderer = new Proxy({}, {
    get(_, prop) {
      return () => {
        throw new Error(
          \`ipcRenderer.\${String(prop)}() cannot be used in a Web Worker. \\n\` +
          'See: https://github.com/electron-vite/vite-plugin-electron/issues/69'
        );
      };
    }
  });
} else {
  _ipcRenderer = electron.ipcRenderer;
}

// Default export
export default electron;

// Renderer process APIs
export const clipboard = electron.clipboard;
export const contextBridge = electron.contextBridge;
export const crashReporter = electron.crashReporter;
export const ipcRenderer = _ipcRenderer;
export const nativeImage = electron.nativeImage;
export const shell = electron.shell;
export const webFrame = electron.webFrame;
export const deprecate = electron.deprecate;

// Main process APIs - exported as undefined for compatibility with packages that check for them
${mainOnlyApis
  .map((name) => `export const ${name} = electron.${name};`)
  .join("\n")}
`.trim();
}

/**
 * Generate ESM wrapper snippet for a CommonJS module
 * Uses require() to load the module and re-exports with ESM syntax
 */
export function generateCjsWrapperSnippet(
  moduleName: string,
  moduleExports: string[]
): string {
  const exportStatements = moduleExports
    .filter((exp) => exp !== "default")
    .map((exp) => `export const ${exp} = _module.${exp};`)
    .join("\n");

  return `
/**
 * ESM wrapper for ${moduleName}
 * Auto-generated by plugin-vite-electron-renderer
 */

// Avoid bundler parsing the require call
const _require = require;
const _module = _require("${moduleName}");

// Default export
export default _module.default || _module;

// Named exports
${exportStatements}
`.trim();
}

/**
 * Generate ESM wrapper snippet for a pre-bundled module
 */
export function generatePreBundledSnippet(
  requirePath: string,
  moduleExports: string[]
): string {
  const exportStatements = moduleExports
    .filter((exp) => exp !== "default")
    .map((exp) => `export const ${exp} = _module.${exp};`)
    .join("\n");

  return `
/**
 * ESM wrapper for pre-bundled module
 * Auto-generated by plugin-vite-electron-renderer
 */

// Avoid bundler parsing the require call
const _require = require;
const _module = _require("${requirePath}");

// Default export
export default _module.default || _module;

// Named exports
${exportStatements}
`.trim();
}

/**
 * Generate simple ESM wrapper for Node.js builtins
 */
export function generateBuiltinSnippet(moduleName: string): string {
  // For node builtins, we need to get the actual exports dynamically
  return `
/**
 * ESM wrapper for Node.js builtin: ${moduleName}
 * Auto-generated by plugin-vite-electron-renderer
 */

const _require = require;
const _module = _require("${moduleName}");

export default _module.default || _module;

// Re-export all enumerable properties
const _keys = Object.keys(_module);
${Array.from(
  { length: 50 },
  (_, i) => `
export const __export_${i}__ = _keys[${i}] ? _module[_keys[${i}]] : undefined;
`
).join("")}

// Common Node.js module exports
export const {
  // fs
  readFile, readFileSync, writeFile, writeFileSync, existsSync, mkdirSync, readdirSync,
  statSync, unlinkSync, renameSync, copyFileSync, appendFileSync, createReadStream, createWriteStream,
  // path
  join, resolve, dirname, basename, extname, relative, isAbsolute, normalize, parse, format, sep, delimiter,
  // events
  EventEmitter,
  // stream
  Readable, Writable, Transform, Duplex, PassThrough, pipeline, finished,
  // util
  promisify, inspect, format: utilFormat, deprecate: utilDeprecate,
  // crypto
  createHash, createHmac, randomBytes, randomUUID,
  // child_process
  spawn, exec, execSync, execFile, fork,
  // os
  platform, arch, homedir, tmpdir, hostname, cpus, totalmem, freemem,
  // url
  URL, URLSearchParams, fileURLToPath, pathToFileURL,
  // http/https
  request, get, createServer,
  // buffer
  Buffer,
  // process
  cwd, env, argv, exit, nextTick,
} = _module;
`.trim();
}

/**
 * Get module exports using require (for CJS modules)
 * This is used at build time to determine what exports a module has
 */
export function getModuleExports(moduleName: string): string[] {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require(moduleName);
    return Object.getOwnPropertyNames(mod);
  } catch {
    return ["default"];
  }
}
